package p153l;

import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import com.p051p1.mobile.putong.live.livingroom.base.player.LivePlayerView;
import com.p051p1.mobile.putong.live.livingroom.base.player.LiveRtcPlayErrorView;
import com.p051p1.mobile.putong.live.livingroom.base.room.LiveBgView;
import com.p051p1.mobile.putong.live.livingroom.base.room.RoomView;
import com.p051p1.mobile.putong.live.livingroom.common.avatar.AvatarView;
import com.p051p1.mobile.putong.live.livingroom.common.bottom.sticker.RoomStickerContainer;
import com.p051p1.mobile.putong.live.livingroom.common.bottom.view.BottomView;
import com.p051p1.mobile.putong.live.livingroom.common.bubble.LiveBubbleView;
import com.p051p1.mobile.putong.live.livingroom.common.chat.ChatView;
import com.p051p1.mobile.putong.live.livingroom.common.chat.danmaku.show.DanmakuViewPort;
import com.p051p1.mobile.putong.live.livingroom.common.chat.inputEntry.ChatInputEntryView;
import com.p051p1.mobile.putong.live.livingroom.common.fans.FansView;
import com.p051p1.mobile.putong.live.livingroom.common.jumproom.JumpToRoomView;
import com.p051p1.mobile.putong.live.livingroom.increment.bullet.BulletView;
import com.p051p1.mobile.putong.live.livingroom.increment.campaign.LiveCampaignView;
import com.p051p1.mobile.putong.live.livingroom.increment.gift.game.GameEffectView;
import com.p051p1.mobile.putong.live.livingroom.increment.gift.giftlayer.LiveGiftLayer;
import com.p051p1.mobile.putong.live.livingroom.increment.gift.topeffect.view.TopEffectLayer;
import com.p051p1.mobile.putong.live.livingroom.increment.gift.tray.LiveEnterRoomView;
import com.p051p1.mobile.putong.live.livingroom.increment.gift.tray.LiveGiftTrays;
import com.p051p1.mobile.putong.live.livingroom.increment.leaderboard.hourleaderboard.entry.HourBoardEntryView;
import com.p051p1.mobile.putong.live.livingroom.increment.leaderboard.hourleaderboard.entry.HourBoardNewEntryView;
import com.p051p1.mobile.putong.live.livingroom.increment.leaderboard.intlstarboard.IntlLiveStarBoardEntryView;
import com.p051p1.mobile.putong.live.livingroom.increment.leaderboard.starboard.StarBoardEntryView;
import com.p051p1.mobile.putong.live.livingroom.increment.operation.OperationEntryView;
import com.p051p1.mobile.putong.live.livingroom.increment.operation.PreOperationAnimView;
import com.p051p1.mobile.putong.live.livingroom.intl.gift.IntlGiftComboView;
import com.p051p1.mobile.putong.live.livingroom.other.side.entry.LiveSiderEntryView;
import com.p051p1.mobile.putong.live.livingroom.recreation.multiCall.annoncements.view.LiveAnnouncementEntryView;
import com.p051p1.mobile.putong.live.livingroom.recreation.multiCall.view.MultiCallTopView;
import com.p051p1.mobile.putong.live.livingroom.recreation.multiPk.multiPkPlaying.MultiPkTimerView;
import com.p051p1.mobile.putong.live.livingroom.recreation.multiplayerchat.view.CallWidgetView;
import com.p051p1.mobile.putong.live.livingroom.recreation.multiplayerchat.view.LiveCallView;
import com.p051p1.mobile.putong.live.livingroom.recreation.multiplayerchat.view.RoomPusherView;
import com.p051p1.mobile.putong.live.livingroom.recreation.p067pk.PkView;
import com.p051p1.mobile.putong.live.livingroom.recreation.p067pk.internal.PkViewInternal;
import com.p051p1.mobile.putong.live.livingroom.view.TouchSwallowView;
import p151v.VFrame;
import p151v.VImage;
import p151v.VRelative;
import p151v.VText;

/* JADX INFO: loaded from: classes4.dex */
public class imd0 {
    /* JADX INFO: renamed from: a */
    public static void m140922a(RoomView roomView, View view) {
        roomView.f48777a = (RoomView) view;
        ViewGroup viewGroup = (ViewGroup) view;
        roomView.f48778b = (LiveBgView) viewGroup.getChildAt(0);
        roomView.f48779c = (LivePlayerView) viewGroup.getChildAt(1);
        roomView.f48780d = (RoomPusherView) viewGroup.getChildAt(2);
        roomView.f48781e = viewGroup.getChildAt(3);
        roomView.f48782f = (LiveRtcPlayErrorView) viewGroup.getChildAt(4);
        roomView.f48783g = (VFrame) viewGroup.getChildAt(5);
        roomView.f48784h = (VRelative) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0);
        roomView.f48785i = (JumpToRoomView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(0);
        roomView.f48786j = (PkView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(1);
        roomView.f48787k = (PkViewInternal) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(2);
        roomView.f48789l = (MultiCallTopView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(3);
        roomView.f48790m = (MultiPkTimerView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(4);
        roomView.f48791n = (VText) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(5);
        roomView.f48792o = (LiveCallView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(6);
        roomView.f48793p = (VFrame) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(7);
        roomView.f48795q = (AvatarView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(7)).getChildAt(0);
        roomView.f48796r = (VRelative) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(8);
        roomView.f48797s = (LiveAnnouncementEntryView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(8)).getChildAt(0);
        roomView.f48798t = (VFrame) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(8)).getChildAt(1);
        roomView.f48799u = (HourBoardEntryView) ((ViewGroup) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(8)).getChildAt(1)).getChildAt(0);
        roomView.f48800v = (HourBoardNewEntryView) ((ViewGroup) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(8)).getChildAt(1)).getChildAt(1);
        roomView.f48801w = (FrameLayout) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(8)).getChildAt(2);
        roomView.f48802x = (StarBoardEntryView) ((ViewGroup) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(8)).getChildAt(2)).getChildAt(0);
        roomView.f48803y = (IntlLiveStarBoardEntryView) ((ViewGroup) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(8)).getChildAt(2)).getChildAt(1);
        roomView.f48804z = (RoomStickerContainer) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(9);
        roomView.f48746A = (TouchSwallowView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(10);
        roomView.f48747B = (OperationEntryView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(10)).getChildAt(0);
        roomView.f48748C = (BulletView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(11);
        roomView.f48749D = (LiveSiderEntryView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(12);
        roomView.f48750E = (TouchSwallowView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(13);
        roomView.f48752F = (FansView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(13)).getChildAt(0);
        roomView.f48754G = (CallWidgetView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(14);
        roomView.f48756H = (LiveCampaignView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(15);
        roomView.f48758I = (TouchSwallowView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(16);
        roomView.f48760J = (ChatView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(16)).getChildAt(0);
        roomView.f48762K = (DanmakuViewPort) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(17);
        roomView.f48764L = (IntlGiftComboView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(1)).getChildAt(0);
        roomView.f48766M = (VFrame) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(2);
        roomView.f48767N = (LiveGiftLayer) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(2)).getChildAt(0);
        roomView.f48768O = (TopEffectLayer) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(2)).getChildAt(1);
        roomView.f48769P = (VRelative) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3);
        roomView.f48770Q = (ChatInputEntryView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3)).getChildAt(0);
        roomView.f48771R = (BottomView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3)).getChildAt(1);
        roomView.f48772S = (LiveBubbleView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3)).getChildAt(2);
        roomView.f48773T = (FrameLayout) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3)).getChildAt(3)).getChildAt(0);
        roomView.f48774U = (LiveGiftTrays) ((ViewGroup) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3)).getChildAt(3)).getChildAt(0)).getChildAt(0);
        roomView.f48775V = (LiveEnterRoomView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3)).getChildAt(3)).getChildAt(1);
        roomView.f48776W = (LiveEnterRoomView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3)).getChildAt(3)).getChildAt(1);
        roomView.f48788k0 = ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3)).getChildAt(4);
        roomView.f48794p0 = (PreOperationAnimView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3)).getChildAt(5)).getChildAt(0);
        roomView.f48751E0 = (FrameLayout) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3)).getChildAt(6);
        roomView.f48753F0 = (VRelative) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3)).getChildAt(7);
        roomView.f48755G0 = (VImage) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3)).getChildAt(7)).getChildAt(0);
        roomView.f48757H0 = (GameEffectView) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(4);
        roomView.f48759I0 = (VFrame) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(5);
        roomView.f48761J0 = (VRelative) viewGroup.getChildAt(6);
    }
}
