package p153l;

import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import com.p051p1.mobile.putong.live.livingroom.base.live.LiveView;
import com.p051p1.mobile.putong.live.livingroom.base.preview.PreviewView;
import com.p051p1.mobile.putong.live.livingroom.base.pusher.LivePusherView;
import com.p051p1.mobile.putong.live.livingroom.base.room.LiveBgView;
import com.p051p1.mobile.putong.live.livingroom.common.avatar.AvatarView;
import com.p051p1.mobile.putong.live.livingroom.common.bottom.sticker.LiveStickerContainer;
import com.p051p1.mobile.putong.live.livingroom.common.bottom.sticker.LiveStickerDragMask;
import com.p051p1.mobile.putong.live.livingroom.common.bottom.view.BottomView;
import com.p051p1.mobile.putong.live.livingroom.common.bubble.LiveBubbleView;
import com.p051p1.mobile.putong.live.livingroom.common.chat.ChatView;
import com.p051p1.mobile.putong.live.livingroom.common.chat.danmaku.show.DanmakuViewPort;
import com.p051p1.mobile.putong.live.livingroom.common.chat.inputEntry.ChatInputEntryView;
import com.p051p1.mobile.putong.live.livingroom.common.fans.FansView;
import com.p051p1.mobile.putong.live.livingroom.increment.bullet.BulletView;
import com.p051p1.mobile.putong.live.livingroom.increment.campaign.LiveCampaignView;
import com.p051p1.mobile.putong.live.livingroom.increment.gift.game.GameEffectView;
import com.p051p1.mobile.putong.live.livingroom.increment.gift.giftlayer.LiveGiftLayer;
import com.p051p1.mobile.putong.live.livingroom.increment.gift.topeffect.view.TopEffectLayer;
import com.p051p1.mobile.putong.live.livingroom.increment.gift.tray.LiveEnterRoomView;
import com.p051p1.mobile.putong.live.livingroom.increment.gift.tray.LiveGiftTrays;
import com.p051p1.mobile.putong.live.livingroom.increment.leaderboard.hourleaderboard.entry.HourBoardEntryView;
import com.p051p1.mobile.putong.live.livingroom.increment.leaderboard.hourleaderboard.entry.HourBoardNewEntryView;
import com.p051p1.mobile.putong.live.livingroom.increment.leaderboard.intlstarboard.IntlLiveStarBoardEntryView;
import com.p051p1.mobile.putong.live.livingroom.increment.leaderboard.starboard.StarBoardEntryView;
import com.p051p1.mobile.putong.live.livingroom.increment.operation.OperationEntryView;
import com.p051p1.mobile.putong.live.livingroom.increment.operation.PreOperationAnimView;
import com.p051p1.mobile.putong.live.livingroom.other.obs.ObsPreviewView;
import com.p051p1.mobile.putong.live.livingroom.recreation.multiCall.annoncements.view.LiveAnnouncementEntryView;
import com.p051p1.mobile.putong.live.livingroom.recreation.multiCall.view.MultiCallTopView;
import com.p051p1.mobile.putong.live.livingroom.recreation.multiPk.multiPkPlaying.MultiPkTimerView;
import com.p051p1.mobile.putong.live.livingroom.recreation.multiplayerchat.view.CallWidgetView;
import com.p051p1.mobile.putong.live.livingroom.recreation.multiplayerchat.view.LiveCallView;
import com.p051p1.mobile.putong.live.livingroom.recreation.p067pk.PkView;
import com.p051p1.mobile.putong.live.livingroom.recreation.p067pk.internal.PkViewInternal;
import p151v.VFrame;
import p151v.VImage;
import p151v.VRelative;

/* JADX INFO: loaded from: classes4.dex */
public class kyu {
    /* JADX INFO: renamed from: a */
    public static void m152141a(LiveView liveView, View view) {
        ViewGroup viewGroup = (ViewGroup) view;
        liveView.f48672a = (LiveBgView) viewGroup.getChildAt(0);
        liveView.f48673b = (LivePusherView) viewGroup.getChildAt(1);
        liveView.f48674c = (PreviewView) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(0);
        liveView.f48675d = (PkView) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(1);
        liveView.f48676e = (PkViewInternal) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(2);
        liveView.f48677f = (MultiCallTopView) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(3);
        liveView.f48678g = (MultiPkTimerView) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(4);
        liveView.f48679h = (ObsPreviewView) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(5);
        liveView.f48680i = (LiveCallView) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(6);
        liveView.f48681j = (VFrame) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(7);
        liveView.f48682k = (AvatarView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(7)).getChildAt(0);
        liveView.f48683l = ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(8);
        liveView.f48684m = (VRelative) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(9);
        liveView.f48685n = (LiveAnnouncementEntryView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(9)).getChildAt(0);
        liveView.f48686o = (VFrame) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(9)).getChildAt(1);
        liveView.f48687p = (HourBoardEntryView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(9)).getChildAt(1)).getChildAt(0);
        liveView.f48688q = (HourBoardNewEntryView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(9)).getChildAt(1)).getChildAt(1);
        liveView.f48689r = (FrameLayout) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(9)).getChildAt(2);
        liveView.f48690s = (StarBoardEntryView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(9)).getChildAt(2)).getChildAt(0);
        liveView.f48691t = (IntlLiveStarBoardEntryView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(9)).getChildAt(2)).getChildAt(1);
        liveView.f48692u = (FansView) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(10);
        liveView.f48693v = (BulletView) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(11);
        liveView.f48694w = (LiveStickerContainer) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(12);
        liveView.f48695x = (OperationEntryView) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(13);
        liveView.f48696y = ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(14);
        liveView.f48697z = (CallWidgetView) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(15);
        liveView.f48649A = (DanmakuViewPort) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(16);
        liveView.f48650B = (ChatView) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(17);
        liveView.f48651C = (LiveCampaignView) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(18);
        liveView.f48652D = (FrameLayout) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(19);
        liveView.f48653E = (VFrame) viewGroup.getChildAt(3);
        liveView.f48654F = (LiveGiftLayer) ((ViewGroup) viewGroup.getChildAt(3)).getChildAt(0);
        liveView.f48655G = (TopEffectLayer) ((ViewGroup) viewGroup.getChildAt(3)).getChildAt(1);
        liveView.f48656H = (VRelative) viewGroup.getChildAt(4);
        liveView.f48657I = (ChatInputEntryView) ((ViewGroup) viewGroup.getChildAt(4)).getChildAt(0);
        liveView.f48658J = (BottomView) ((ViewGroup) viewGroup.getChildAt(4)).getChildAt(1);
        liveView.f48659K = (LiveBubbleView) ((ViewGroup) viewGroup.getChildAt(4)).getChildAt(2);
        liveView.f48660L = (LiveGiftTrays) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(4)).getChildAt(3)).getChildAt(0);
        liveView.f48661M = (LiveEnterRoomView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(4)).getChildAt(3)).getChildAt(1);
        liveView.f48662N = (LiveEnterRoomView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(4)).getChildAt(3)).getChildAt(1);
        liveView.f48663O = (FrameLayout) ((ViewGroup) viewGroup.getChildAt(4)).getChildAt(4);
        liveView.f48664P = (VRelative) viewGroup.getChildAt(5);
        liveView.f48665Q = (VImage) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0);
        liveView.f48666R = (LiveStickerDragMask) viewGroup.getChildAt(6);
        liveView.f48667S = viewGroup.getChildAt(7);
        liveView.f48668T = (PreOperationAnimView) viewGroup.getChildAt(8);
        liveView.f48669U = (GameEffectView) viewGroup.getChildAt(9);
        liveView.f48670V = (VFrame) viewGroup.getChildAt(10);
    }
}
