package p153l;

import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import com.p051p1.mobile.putong.live.livingroom.common.chat.danmaku.show.DanmakuViewPort;
import com.p051p1.mobile.putong.live.livingroom.common.chat.list.ChatListView;
import com.p051p1.mobile.putong.live.livingroom.increment.campaign.LiveCampaignView;
import com.p051p1.mobile.putong.live.livingroom.increment.gift.giftlayer.LiveGiftLayer;
import com.p051p1.mobile.putong.live.livingroom.increment.gift.topeffect.view.TopEffectLayer;
import com.p051p1.mobile.putong.live.livingroom.increment.gift.tray.LiveEnterRoomView;
import com.p051p1.mobile.putong.live.livingroom.increment.gift.tray.LiveGiftTrays;
import com.p051p1.mobile.putong.live.livingroom.increment.leaderboard.intlstarboard.IntlLiveStarBoardEntryView;
import com.p051p1.mobile.putong.live.livingroom.intl.gift.IntlGiftComboView;
import com.p051p1.mobile.putong.live.livingroom.view.TouchSwallowView;
import com.p051p1.mobile.putong.live.livingroom.voice.applymanager.VoiceLiveApplyManagerEnterViewModel;
import com.p051p1.mobile.putong.live.livingroom.voice.basebuild.notice.VoiceTopNoticeView;
import com.p051p1.mobile.putong.live.livingroom.voice.bottom.BottomMenuView;
import com.p051p1.mobile.putong.live.livingroom.voice.bottom.VoiceBottomView;
import com.p051p1.mobile.putong.live.livingroom.voice.bubble.VoiceLiveBubbleView;
import com.p051p1.mobile.putong.live.livingroom.voice.chat.view.VoiceChatBottomView;
import com.p051p1.mobile.putong.live.livingroom.voice.fans.VoiceFansView;
import com.p051p1.mobile.putong.live.livingroom.voice.grabhat.view.VoiceGrabHatFloatViewMode;
import com.p051p1.mobile.putong.live.livingroom.voice.intl.chatgroup.VoiceChatGroupEnterView;
import com.p051p1.mobile.putong.live.livingroom.voice.intl.close.VoiceCloseView;
import com.p051p1.mobile.putong.live.livingroom.voice.intl.flymic.VoiceFlyMicContainer;
import com.p051p1.mobile.putong.live.livingroom.voice.intl.game.gameRoot.VoiceNewGamePlayRootView;
import com.p051p1.mobile.putong.live.livingroom.voice.intl.heartbeat.VoiceTopHeartBeatView;
import com.p051p1.mobile.putong.live.livingroom.voice.intl.heatbox.VoiceLiveHeatBoxEntryView;
import com.p051p1.mobile.putong.live.livingroom.voice.intl.increment.bullet.VoiceLiveBulletView;
import com.p051p1.mobile.putong.live.livingroom.voice.intl.increment.leaderboard.hourleaderboard.widget.VoiceLiveHourBoardEntryView;
import com.p051p1.mobile.putong.live.livingroom.voice.intl.newoperation.VoiceNewOperationView;
import com.p051p1.mobile.putong.live.livingroom.voice.intl.operations.VoiceOperationsView;
import com.p051p1.mobile.putong.live.livingroom.voice.intl.p069pk.VoicePkMvpView;
import com.p051p1.mobile.putong.live.livingroom.voice.intl.p069pk.VoicePkTimeView;
import com.p051p1.mobile.putong.live.livingroom.voice.intl.player.VoiceIncomeAreaStateView;
import com.p051p1.mobile.putong.live.livingroom.voice.intl.player.VoiceOrignalStateView;
import com.p051p1.mobile.putong.live.livingroom.voice.intl.player.VoiceRoomLoadingView;
import com.p051p1.mobile.putong.live.livingroom.voice.intl.roombg.common.VoiceBackgroundView;
import com.p051p1.mobile.putong.live.livingroom.voice.intl.roominfobar.VoiceRoomInfoView;
import com.p051p1.mobile.putong.live.livingroom.voice.intl.root.VoiceRoomView;
import p151v.VFrame;

/* JADX INFO: loaded from: classes4.dex */
public class sro0 {
    /* JADX INFO: renamed from: a */
    public static void m187631a(VoiceRoomView voiceRoomView, View view) {
        voiceRoomView.f54329d = (VoiceRoomView) view;
        ViewGroup viewGroup = (ViewGroup) view;
        voiceRoomView.f54330e = (VoiceBackgroundView) viewGroup.getChildAt(0);
        voiceRoomView.f54331f = (TouchSwallowView) viewGroup.getChildAt(1);
        voiceRoomView.f54332g = (VoiceFansView) ((ViewGroup) viewGroup.getChildAt(1)).getChildAt(0);
        voiceRoomView.f54333h = (VoiceCloseView) viewGroup.getChildAt(2);
        voiceRoomView.f54334i = (VoicePkMvpView) viewGroup.getChildAt(3);
        voiceRoomView.f54335j = (VoiceRoomInfoView) viewGroup.getChildAt(4);
        voiceRoomView.f54336k = (LiveCampaignView) viewGroup.getChildAt(5);
        voiceRoomView.f54338l = (VoiceNewOperationView) viewGroup.getChildAt(6);
        voiceRoomView.f54339m = (FrameLayout) viewGroup.getChildAt(7);
        voiceRoomView.f54340n = (TouchSwallowView) viewGroup.getChildAt(8);
        voiceRoomView.f54341o = (VoiceOperationsView) ((ViewGroup) viewGroup.getChildAt(8)).getChildAt(0);
        voiceRoomView.f54342p = (RecyclerView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(8)).getChildAt(0)).getChildAt(0);
        voiceRoomView.f54344q = (ConstraintLayout) viewGroup.getChildAt(9);
        voiceRoomView.f54345r = (VoiceTopHeartBeatView) ((ViewGroup) viewGroup.getChildAt(9)).getChildAt(0);
        voiceRoomView.f54346s = (IntlLiveStarBoardEntryView) ((ViewGroup) viewGroup.getChildAt(9)).getChildAt(1);
        voiceRoomView.f54347t = (VoiceLiveHourBoardEntryView) ((ViewGroup) viewGroup.getChildAt(9)).getChildAt(2);
        voiceRoomView.f54348u = (VoiceLiveHeatBoxEntryView) ((ViewGroup) viewGroup.getChildAt(9)).getChildAt(3);
        voiceRoomView.f54349v = (VoiceTopNoticeView) ((ViewGroup) viewGroup.getChildAt(9)).getChildAt(4);
        voiceRoomView.f54350w = (VoiceChatGroupEnterView) ((ViewGroup) viewGroup.getChildAt(9)).getChildAt(5);
        voiceRoomView.f54351x = (VoiceLiveApplyManagerEnterViewModel) viewGroup.getChildAt(10);
        voiceRoomView.f54352y = (VoiceIncomeAreaStateView) viewGroup.getChildAt(11);
        voiceRoomView.f54353z = (VFrame) viewGroup.getChildAt(12);
        voiceRoomView.f54298A = (VoiceOrignalStateView) ((ViewGroup) viewGroup.getChildAt(12)).getChildAt(0);
        voiceRoomView.f54299B = (VoiceNewGamePlayRootView) viewGroup.getChildAt(13);
        voiceRoomView.f54300C = viewGroup.getChildAt(14);
        voiceRoomView.f54301D = (TouchSwallowView) viewGroup.getChildAt(15);
        voiceRoomView.f54302E = (ChatListView) ((ViewGroup) viewGroup.getChildAt(15)).getChildAt(0);
        voiceRoomView.f54304F = (VoicePkTimeView) viewGroup.getChildAt(16);
        voiceRoomView.f54306G = (VoiceGrabHatFloatViewMode) viewGroup.getChildAt(17);
        voiceRoomView.f54308H = (FrameLayout) viewGroup.getChildAt(18);
        voiceRoomView.f54310I = viewGroup.getChildAt(19);
        voiceRoomView.f54312J = (TouchSwallowView) viewGroup.getChildAt(20);
        voiceRoomView.f54314K = (VoiceBottomView) ((ViewGroup) viewGroup.getChildAt(20)).getChildAt(0);
        voiceRoomView.f54316L = (VoiceChatBottomView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(20)).getChildAt(0)).getChildAt(0);
        voiceRoomView.f54318M = (BottomMenuView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(20)).getChildAt(0)).getChildAt(1);
        voiceRoomView.f54319N = (VoiceRoomLoadingView) viewGroup.getChildAt(21);
        voiceRoomView.f54320O = (TouchSwallowView) viewGroup.getChildAt(22);
        voiceRoomView.f54321P = (LiveGiftTrays) ((ViewGroup) viewGroup.getChildAt(22)).getChildAt(0);
        voiceRoomView.f54322Q = (DanmakuViewPort) viewGroup.getChildAt(23);
        voiceRoomView.f54323R = (TouchSwallowView) viewGroup.getChildAt(24);
        voiceRoomView.f54324S = (FrameLayout) ((ViewGroup) viewGroup.getChildAt(24)).getChildAt(0);
        voiceRoomView.f54325T = (IntlGiftComboView) ((ViewGroup) viewGroup.getChildAt(25)).getChildAt(0);
        voiceRoomView.f54326U = (VoiceLiveBulletView) viewGroup.getChildAt(26);
        voiceRoomView.f54327V = (VFrame) viewGroup.getChildAt(27);
        voiceRoomView.f54328W = (VoiceFlyMicContainer) ((ViewGroup) viewGroup.getChildAt(27)).getChildAt(0);
        voiceRoomView.f54337k0 = (LiveGiftLayer) ((ViewGroup) viewGroup.getChildAt(27)).getChildAt(1);
        voiceRoomView.f54343p0 = (TopEffectLayer) ((ViewGroup) viewGroup.getChildAt(27)).getChildAt(2);
        voiceRoomView.f54303E0 = (LiveEnterRoomView) viewGroup.getChildAt(28);
        voiceRoomView.f54305F0 = (LiveEnterRoomView) viewGroup.getChildAt(28);
        voiceRoomView.f54307G0 = (VFrame) viewGroup.getChildAt(29);
        voiceRoomView.f54309H0 = (VoiceLiveBubbleView) ((ViewGroup) viewGroup.getChildAt(29)).getChildAt(0);
        voiceRoomView.f54311I0 = ((ViewGroup) viewGroup.getChildAt(29)).getChildAt(1);
        voiceRoomView.f54313J0 = (FrameLayout) viewGroup.getChildAt(30);
    }
}
