package p153l;

import android.view.View;
import android.view.ViewGroup;
import android.view.ViewStub;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.Space;
import android.widget.TextView;
import com.p051p1.mobile.putong.core.newui.home.NewNewProfileCard;
import com.p051p1.mobile.putong.core.newui.home.NewPictureContainerIndicator;
import com.p051p1.mobile.putong.core.newui.home.views.CardBottomDefaultLayout;
import com.p051p1.mobile.putong.core.newui.home.views.CardBottomIntlLiveLayout;
import com.p051p1.mobile.putong.core.newui.home.views.CardBottomIntlVoiceLayout;
import com.p051p1.mobile.putong.core.newui.home.views.CardBottomLiveView;
import com.p051p1.mobile.putong.core.newui.home.views.CardBottomMomentCardTwoView;
import com.p051p1.mobile.putong.core.newui.home.views.CardBottomMomentGreetView;
import com.p051p1.mobile.putong.core.newui.home.views.CardBottomMomentLayout;
import com.p051p1.mobile.putong.core.newui.home.views.CardBottomTagLayout;
import com.p051p1.mobile.putong.core.newui.home.views.SuperLikeBanner;
import com.p051p1.mobile.putong.core.newui.home.views.SwipeLikeButton;
import com.p051p1.mobile.putong.core.newui.view.LinearMeasureOrderLayout;
import com.p051p1.mobile.putong.core.p058ui.PictureView;
import com.p051p1.mobile.putong.core.p058ui.likeminded.LikeMindedCardTabView;
import com.tantan.library.svga.SVGAnimationView;
import p151v.VDraweeView;
import p151v.VFrame;
import p151v.VIcon;
import p151v.VImage;
import p151v.VLinear;
import p151v.VText;

/* JADX INFO: loaded from: classes10.dex */
public class w740 {
    /* JADX INFO: renamed from: a */
    public static void m205227a(NewNewProfileCard newNewProfileCard, View view) {
        newNewProfileCard.f22457M = (NewNewProfileCard) view;
        ViewGroup viewGroup = (ViewGroup) view;
        newNewProfileCard.f22461N = (LinearLayout) viewGroup.getChildAt(0);
        newNewProfileCard.f22464O = ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(0);
        newNewProfileCard.f22467P = (VLinear) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(1);
        newNewProfileCard.f22470Q = ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(1)).getChildAt(0);
        newNewProfileCard.f22473R = (CardBottomMomentCardTwoView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(1)).getChildAt(1);
        newNewProfileCard.f22476S = ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(1)).getChildAt(2);
        newNewProfileCard.f22479T = (PictureView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(2);
        newNewProfileCard.f22482U = (Space) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(3);
        newNewProfileCard.f22485V = ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(4);
        newNewProfileCard.f22488W = ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(5);
        newNewProfileCard.f22517k0 = ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(6);
        newNewProfileCard.f22528p0 = ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(7);
        newNewProfileCard.f22433E0 = (LinearMeasureOrderLayout) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8);
        newNewProfileCard.f22436F0 = (VFrame) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(0);
        newNewProfileCard.f22439G0 = (SVGAnimationView) ((ViewGroup) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(0)).getChildAt(0);
        newNewProfileCard.f22442H0 = (VText) ((ViewGroup) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(0)).getChildAt(1);
        newNewProfileCard.f22445I0 = (TextView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(1);
        newNewProfileCard.f22448J0 = (VText) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(2);
        newNewProfileCard.f22451K0 = (VText) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(3);
        newNewProfileCard.f22454L0 = (VLinear) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(4);
        newNewProfileCard.f22458M0 = (ImageView) ((ViewGroup) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(4)).getChildAt(0);
        newNewProfileCard.f22462N0 = (TextView) ((ViewGroup) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(4)).getChildAt(1);
        newNewProfileCard.f22465O0 = (VText) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(5);
        newNewProfileCard.f22468P0 = (VText) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(6);
        newNewProfileCard.f22471Q0 = (VLinear) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(7);
        newNewProfileCard.f22474R0 = (VDraweeView) ((ViewGroup) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(7)).getChildAt(0);
        newNewProfileCard.f22477S0 = (VText) ((ViewGroup) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(7)).getChildAt(1);
        newNewProfileCard.f22480T0 = (VText) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(8);
        newNewProfileCard.f22483U0 = (VImage) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(9);
        newNewProfileCard.f22486V0 = (FrameLayout) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(9);
        newNewProfileCard.f22489W0 = (CardBottomLiveView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(9)).getChildAt(0);
        newNewProfileCard.f22491X0 = (CardBottomMomentGreetView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(9)).getChildAt(1);
        newNewProfileCard.f22493Y0 = (CardBottomDefaultLayout) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(9)).getChildAt(2);
        newNewProfileCard.f22495Z0 = (CardBottomIntlLiveLayout) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(9)).getChildAt(3);
        newNewProfileCard.f22497a1 = (CardBottomIntlVoiceLayout) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(9)).getChildAt(4);
        newNewProfileCard.f22499b1 = (CardBottomTagLayout) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(9)).getChildAt(5);
        newNewProfileCard.f22501c1 = (CardBottomMomentLayout) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(9)).getChildAt(6);
        newNewProfileCard.f22503d1 = (VLinear) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(10);
        newNewProfileCard.f22505e1 = (VIcon) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(11);
        newNewProfileCard.f22507f1 = (VImage) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(12);
        newNewProfileCard.f22509g1 = (VImage) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(13);
        newNewProfileCard.f22511h1 = (ViewStub) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(14);
        newNewProfileCard.f22513i1 = (ViewStub) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(15);
        newNewProfileCard.f22515j1 = (LikeMindedCardTabView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(16);
        newNewProfileCard.f22518k1 = (VLinear) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(17);
        newNewProfileCard.f22520l1 = (VText) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(17)).getChildAt(1);
        newNewProfileCard.f22522m1 = (ViewStub) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(18);
        newNewProfileCard.f22524n1 = (ViewStub) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(19);
        newNewProfileCard.f22526o1 = (ViewStub) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(20);
        newNewProfileCard.f22529p1 = (SuperLikeBanner) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(21);
        newNewProfileCard.f22531q1 = (SwipeLikeButton) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(22);
        newNewProfileCard.f22533r1 = (SwipeLikeButton) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(23);
        newNewProfileCard.f22535s1 = (NewPictureContainerIndicator) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(24);
        newNewProfileCard.f22537t1 = (ViewStub) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(25);
        newNewProfileCard.f22539u1 = (ViewStub) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(26);
        newNewProfileCard.f22541v1 = (ViewStub) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(27);
        newNewProfileCard.f22543w1 = (ViewStub) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(28);
        newNewProfileCard.f22545x1 = (ViewStub) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(29);
        newNewProfileCard.f22547y1 = (LinearLayout) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(30);
        newNewProfileCard.f22549z1 = (VText) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(30)).getChildAt(1);
        newNewProfileCard.f22425A1 = (LinearLayout) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(31);
        newNewProfileCard.f22427B1 = (VText) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(31)).getChildAt(1);
        newNewProfileCard.f22429C1 = (VFrame) viewGroup.getChildAt(1);
        newNewProfileCard.f22431D1 = (ViewStub) ((ViewGroup) viewGroup.getChildAt(1)).getChildAt(0);
    }
}
