package com.p051p1.mobile.putong.util.launch;

/* JADX INFO: loaded from: classes10.dex */
public enum LaunchStep {
    Application("app_start", "Application创建耗时"),
    AppStartArriveImgload("app_start_to_imgload", "app启动到图片加载完成_有广告时排出广告显示时间"),
    PutongArriveImgload("ptong_to_imgload", "putong到图片加载完成_有广告时排出广告显示时间"),
    AppStartArriveImgloadNoAd("app_start_to_imgload_on_ad", "app启动到图片加载完成_无广告"),
    PutongArriveImgloadNoAd("ptong_to_imgload_on_ad", "putong到图片加载完成_无广告"),
    AdConsum("ad_consum", "有广告广告显示时间"),
    NewMainCreate("new_main_create", "首页启动到卡片渲染完毕"),
    NewMainSub("new_main_sub", "首页订阅耗时"),
    NewNewHomeSub("new_new_home_sub", "划卡页订阅耗时"),
    NewMainBaseSub("new_main_base_sub", "首页Base订阅耗时"),
    FirstNet("first_net_load", "卡片数据请求等待"),
    PreNet("pre_net_load", "卡片数据预加载"),
    PreNet_Request("pre_net_request_load", "卡片数据预加载网络耗时"),
    PreNet_Parse("pre_net_parse_load", "卡片数据预加载解析"),
    PreNet_Op("pre_net_op_load", "卡片数据预加载处理数据"),
    PreNet_Db("pre_net_db_load", "卡片数据预加载入库"),
    RenderTask("render_task", "渲染任务"),
    SuggestNet("suggest_net", "卡片数据从订阅到数据回来耗时"),
    AsyncLayout("async_layout", "卡片异步耗时"),
    HomeFragWait("home_create", "从首页启动到划卡页面onCreate耗时"),
    MainActInflate("main_act_inflate", "首页Inflate时间"),
    HomeTabInflate("home_tab_inflate", "划卡页面的Inflate"),
    MsgTabInflate("msg_table_inflate", "配对列表的Inflate"),
    MsgTabDataInit("msg_table_data_init", "配对列表的数据初始化"),
    MsgDoubleTabInflate("msg_double_table_inflate", "双tab配对列表的创建"),
    MsgSearchInflate("msg_search_inflate", "配对列表搜索的创建"),
    FeedTabInflate("feed_table_inflate", "配对列表的创建"),
    MyTabInflate("my_table_inflate", "配对列表的创建"),
    PutongCreate("putong_onCreate", "putong的创建时间"),
    PuginInit("plugin_init", "插件模块创建"),
    NetworkInit("network_init", "Okhttp创建"),
    BaseApi("base_api_init", "BaseApi创建"),
    CityTopSvga("city_top_svga", "city_top_svga"),
    ThemeChange("theme_change", "theme_change"),
    BigEmoji("big_emoji", "big_emoji"),
    BaseApiV2("base_api_init_v2", "BaseApi_V2创建"),
    ImageLoad("imageload_init", "ImageLoad创建"),
    LocationMap("location_map", "LocationMap创建"),
    LocalDataParse("local_data_parse", "本地数据解析"),
    AbLocalInit("ab_local_init", "本地启动Ab解析"),
    RemoteLocalInit("remote_local_init", "Remote本地启动"),
    AccountPluginInit("account_plugin_init", "Account插件启动"),
    PrivacyConfig("privacy_config", "Privacy配置"),
    FbSdk("fb_sdk", "FbSdk初始化"),
    InitAccountModule("init_account_module", "InitAccountModule调用"),
    InitOms("init_oms", "Oms初始化"),
    OmsParse("oms_parse", "Oms解析"),
    MkParse("mk_parse", "Mk解析"),
    InitSignData("init_sign_data", "登录成功后的数据初始化"),
    AccountAfterCreate("account_af_create", "Account创建成功调用"),
    InitOtherModule("init_other_module", "Other模块初始化"),
    InitDb("init_db", "init_db"),
    InitOtherDb("init_other_db", "初始化业务db"),
    SignedStep("signed_step", "登录逻辑"),
    InitMe("init_me", "初始化Me"),
    InitMeSuccess("init_me_success", "初始化Me成功"),
    NotifyMeSuccess("notify_me_success", "通知Me成功"),
    InitCommonInfo("init_common_info", "初始化通用信息"),
    NotifySignIn("notify_sign_in", "通知登录成功"),
    NotifyAllSignIn("notify_all_sign_in", "通知所有模块登录成功"),
    CoreAfterSignIn("core_after_signin", "Core登录成功"),
    CoreOtherAfterSignIn("core_other_after_signin", "Core其他登录成功"),
    EnsureCoreApi("ensure_core_api", "初始化CoreApi"),
    CreateMe("create_me", "创建Me"),
    FeedAfterSignIn("feed_after_signin", "Feed登录成功"),
    WebpCall("webp_fun_call", "Web替换逻辑"),
    SplashCreate("splash_create", "启动页面Create耗时"),
    SplashWaitAb("splash_wait_ab", "启动等待ab"),
    SplashWaitUser("splash_wait_user", "启动等待User"),
    SplashWaitPlugin("splash_wait_plugin", "启动等待Plugin"),
    SoloadInit("soload_init", "So初始化加载"),
    MMKVInit("mmkv_init", "MMkv初始化加载"),
    SafeCreateInit("SafeCreateInit", "SafeCreateInit"),
    InitWebView("InitWebView", "InitWebView"),
    BeginPutongCreate("begin_putong_create", "开始准备创建Putong"),
    SplashStartWait("splash_start_wait", "Splash启动等待"),
    MainStartWait("main_start_wait", "首页启动等待"),
    SplashAll("splash_all", "启动页面总耗时"),
    AdWait("ad_wait", "广告等待"),
    SplashProxyCreate("splash_proxy_create", "启动代理页面Create耗时"),
    SplashProxyAll("splash_proxy_all", "启动代理页面总耗时"),
    SplashWaitModuleLoad("waitModuleLoaded", "启动代理页面waitModuleLoaded"),
    SplashPageCreateWait("SplashPageCreateWait", "启动页面创建等待"),
    PrepareDb("prepare_db", "prepare_db"),
    StartDb("start_db", "start_db"),
    InitAbReal("init_ab_real", "init_ab_real"),
    StartServiceAndDb("start_service_db", "数据库和模块调用"),
    AccountModuleInject("account_module_inject", "AccountModuleInjec调用"),
    DoAccountInit("do_account_init", "DoAccountInit调用"),
    ParsePluginMap("parse_plugin_map", "解析插件Map"),
    MobSdkInit("mob_sdk_init", "MobSdk本地启动"),
    PutongOnNext("putong_onNext", "putong发射OnNext本地启动"),
    DiskCheck("disk_check", "本地空间检测"),
    SvgaInit("svga_init", "Svga启动"),
    BaseAppInit("base_app_init", "App创建"),
    OneIdInit("one_id_init", "OneId创建"),
    PutongAsyncCreate("putong_async_onCreate", "putong异步的创建时间"),
    InitAllTags("init_all_tags", "标签数据初始化"),
    OmsManagerCache("oms_manager_cache", "OmsManager 初始到内存耗时"),
    LiveTabInflate("live_table_inflate", "配对列表的创建");

    private String stepDesc;
    private String stepName;

    LaunchStep(String str, String str2) {
        this.stepName = str;
        this.stepDesc = str2;
    }

    public String getStepDesc() {
        return this.stepDesc;
    }

    public String getStepName() {
        return this.stepName;
    }
}
