package com.tantanapp.media.ttmediamncertification;

/* JADX INFO: loaded from: classes13.dex */
public enum FacertificationSDKType {
    FACERTIFICATION_SDK_TYPE_TX,
    FACERTIFICATION_SDK_TYPE_FPP,
    FACERTIFICATION_SDK_TYPE_ALI,
    FACERTIFICATION_SDK_TYPE_TX_INTL,
    FACERTIFICATION_SDK_TYPE_TX_INTL_V2,
    FACERTIFICATION_SDK_TYPE_MOMO,
    FACERTIFICATION_SDK_TYPE_EXT,
    FACERTIFICATION_SDK_TYPE_ALI_INTL,
    FACERTIFICATION_SDK_TYPE_BYTE_VOLC
}
