package p149l;

import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import com.p046p1.mobile.putong.live.livingroom.base.player.LivePlayerView;
import com.p046p1.mobile.putong.live.livingroom.base.player.LiveRtcPlayErrorView;
import com.p046p1.mobile.putong.live.livingroom.base.room.LiveBgView;
import com.p046p1.mobile.putong.live.livingroom.base.room.RoomView;
import com.p046p1.mobile.putong.live.livingroom.common.avatar.AvatarView;
import com.p046p1.mobile.putong.live.livingroom.common.bottom.sticker.RoomStickerContainer;
import com.p046p1.mobile.putong.live.livingroom.common.bottom.view.BottomView;
import com.p046p1.mobile.putong.live.livingroom.common.bubble.LiveBubbleView;
import com.p046p1.mobile.putong.live.livingroom.common.chat.ChatView;
import com.p046p1.mobile.putong.live.livingroom.common.chat.danmaku.show.DanmakuViewPort;
import com.p046p1.mobile.putong.live.livingroom.common.chat.inputEntry.ChatInputEntryView;
import com.p046p1.mobile.putong.live.livingroom.common.fans.FansView;
import com.p046p1.mobile.putong.live.livingroom.common.jumproom.JumpToRoomView;
import com.p046p1.mobile.putong.live.livingroom.increment.bullet.BulletView;
import com.p046p1.mobile.putong.live.livingroom.increment.campaign.LiveCampaignView;
import com.p046p1.mobile.putong.live.livingroom.increment.gift.game.GameEffectView;
import com.p046p1.mobile.putong.live.livingroom.increment.gift.giftlayer.LiveGiftLayer;
import com.p046p1.mobile.putong.live.livingroom.increment.gift.topeffect.view.TopEffectLayer;
import com.p046p1.mobile.putong.live.livingroom.increment.gift.tray.LiveEnterRoomView;
import com.p046p1.mobile.putong.live.livingroom.increment.gift.tray.LiveGiftTrays;
import com.p046p1.mobile.putong.live.livingroom.increment.leaderboard.hourleaderboard.entry.HourBoardEntryView;
import com.p046p1.mobile.putong.live.livingroom.increment.leaderboard.hourleaderboard.entry.HourBoardNewEntryView;
import com.p046p1.mobile.putong.live.livingroom.increment.leaderboard.intlstarboard.IntlLiveStarBoardEntryView;
import com.p046p1.mobile.putong.live.livingroom.increment.leaderboard.starboard.StarBoardEntryView;
import com.p046p1.mobile.putong.live.livingroom.increment.operation.OperationEntryView;
import com.p046p1.mobile.putong.live.livingroom.increment.operation.PreOperationAnimView;
import com.p046p1.mobile.putong.live.livingroom.intl.gift.IntlGiftComboView;
import com.p046p1.mobile.putong.live.livingroom.other.side.entry.LiveSiderEntryView;
import com.p046p1.mobile.putong.live.livingroom.recreation.multiCall.annoncements.view.LiveAnnouncementEntryView;
import com.p046p1.mobile.putong.live.livingroom.recreation.multiCall.view.MultiCallTopView;
import com.p046p1.mobile.putong.live.livingroom.recreation.multiPk.multiPkPlaying.MultiPkTimerView;
import com.p046p1.mobile.putong.live.livingroom.recreation.multiplayerchat.view.CallWidgetView;
import com.p046p1.mobile.putong.live.livingroom.recreation.multiplayerchat.view.LiveCallView;
import com.p046p1.mobile.putong.live.livingroom.recreation.multiplayerchat.view.RoomPusherView;
import com.p046p1.mobile.putong.live.livingroom.recreation.p062pk.PkView;
import com.p046p1.mobile.putong.live.livingroom.recreation.p062pk.internal.PkViewInternal;
import com.p046p1.mobile.putong.live.livingroom.view.TouchSwallowView;
import p147v.VFrame;
import p147v.VImage;
import p147v.VRelative;
import p147v.VText;

/* JADX INFO: loaded from: classes4.dex */
public class ged0 {
    /* JADX INFO: renamed from: a */
    public static void m125691a(RoomView roomView, View view) {
        roomView.f47929a = (RoomView) view;
        ViewGroup viewGroup = (ViewGroup) view;
        roomView.f47930b = (LiveBgView) viewGroup.getChildAt(0);
        roomView.f47931c = (LivePlayerView) viewGroup.getChildAt(1);
        roomView.f47932d = (RoomPusherView) viewGroup.getChildAt(2);
        roomView.f47933e = viewGroup.getChildAt(3);
        roomView.f47934f = (LiveRtcPlayErrorView) viewGroup.getChildAt(4);
        roomView.f47935g = (VFrame) viewGroup.getChildAt(5);
        roomView.f47936h = (VRelative) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0);
        roomView.f47937i = (JumpToRoomView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(0);
        roomView.f47938j = (PkView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(1);
        roomView.f47939k = (PkViewInternal) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(2);
        roomView.f47941l = (MultiCallTopView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(3);
        roomView.f47942m = (MultiPkTimerView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(4);
        roomView.f47943n = (VText) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(5);
        roomView.f47944o = (LiveCallView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(6);
        roomView.f47945p = (VFrame) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(7);
        roomView.f47947q = (AvatarView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(7)).getChildAt(0);
        roomView.f47948r = (VRelative) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(8);
        roomView.f47949s = (LiveAnnouncementEntryView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(8)).getChildAt(0);
        roomView.f47950t = (VFrame) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(8)).getChildAt(1);
        roomView.f47951u = (HourBoardEntryView) ((ViewGroup) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(8)).getChildAt(1)).getChildAt(0);
        roomView.f47952v = (HourBoardNewEntryView) ((ViewGroup) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(8)).getChildAt(1)).getChildAt(1);
        roomView.f47953w = (FrameLayout) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(8)).getChildAt(2);
        roomView.f47954x = (StarBoardEntryView) ((ViewGroup) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(8)).getChildAt(2)).getChildAt(0);
        roomView.f47955y = (IntlLiveStarBoardEntryView) ((ViewGroup) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(8)).getChildAt(2)).getChildAt(1);
        roomView.f47956z = (RoomStickerContainer) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(9);
        roomView.f47898A = (TouchSwallowView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(10);
        roomView.f47899B = (OperationEntryView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(10)).getChildAt(0);
        roomView.f47900C = (BulletView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(11);
        roomView.f47901D = (LiveSiderEntryView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(12);
        roomView.f47902E = (TouchSwallowView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(13);
        roomView.f47904F = (FansView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(13)).getChildAt(0);
        roomView.f47906G = (CallWidgetView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(14);
        roomView.f47908H = (LiveCampaignView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(15);
        roomView.f47910I = (TouchSwallowView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(16);
        roomView.f47912J = (ChatView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(16)).getChildAt(0);
        roomView.f47914K = (DanmakuViewPort) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0)).getChildAt(17);
        roomView.f47916L = (IntlGiftComboView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(1)).getChildAt(0);
        roomView.f47918M = (VFrame) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(2);
        roomView.f47919N = (LiveGiftLayer) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(2)).getChildAt(0);
        roomView.f47920O = (TopEffectLayer) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(2)).getChildAt(1);
        roomView.f47921P = (VRelative) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3);
        roomView.f47922Q = (ChatInputEntryView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3)).getChildAt(0);
        roomView.f47923R = (BottomView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3)).getChildAt(1);
        roomView.f47924S = (LiveBubbleView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3)).getChildAt(2);
        roomView.f47925T = (FrameLayout) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3)).getChildAt(3)).getChildAt(0);
        roomView.f47926U = (LiveGiftTrays) ((ViewGroup) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3)).getChildAt(3)).getChildAt(0)).getChildAt(0);
        roomView.f47927V = (LiveEnterRoomView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3)).getChildAt(3)).getChildAt(1);
        roomView.f47928W = (LiveEnterRoomView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3)).getChildAt(3)).getChildAt(1);
        roomView.f47940k0 = ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3)).getChildAt(4);
        roomView.f47946p0 = (PreOperationAnimView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3)).getChildAt(5)).getChildAt(0);
        roomView.f47903E0 = (FrameLayout) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3)).getChildAt(6);
        roomView.f47905F0 = (VRelative) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3)).getChildAt(7);
        roomView.f47907G0 = (VImage) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(3)).getChildAt(7)).getChildAt(0);
        roomView.f47909H0 = (GameEffectView) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(4);
        roomView.f47911I0 = (VFrame) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(5);
        roomView.f47913J0 = (VRelative) viewGroup.getChildAt(6);
    }
}
