package p149l;

import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import com.p046p1.mobile.putong.live.livingroom.common.chat.danmaku.show.DanmakuViewPort;
import com.p046p1.mobile.putong.live.livingroom.common.chat.list.ChatListView;
import com.p046p1.mobile.putong.live.livingroom.increment.campaign.LiveCampaignView;
import com.p046p1.mobile.putong.live.livingroom.increment.gift.giftlayer.LiveGiftLayer;
import com.p046p1.mobile.putong.live.livingroom.increment.gift.topeffect.view.TopEffectLayer;
import com.p046p1.mobile.putong.live.livingroom.increment.gift.tray.LiveEnterRoomView;
import com.p046p1.mobile.putong.live.livingroom.increment.gift.tray.LiveGiftTrays;
import com.p046p1.mobile.putong.live.livingroom.increment.leaderboard.intlstarboard.IntlLiveStarBoardEntryView;
import com.p046p1.mobile.putong.live.livingroom.intl.gift.IntlGiftComboView;
import com.p046p1.mobile.putong.live.livingroom.view.TouchSwallowView;
import com.p046p1.mobile.putong.live.livingroom.voice.applymanager.VoiceLiveApplyManagerEnterViewModel;
import com.p046p1.mobile.putong.live.livingroom.voice.basebuild.notice.VoiceTopNoticeView;
import com.p046p1.mobile.putong.live.livingroom.voice.bottom.BottomMenuView;
import com.p046p1.mobile.putong.live.livingroom.voice.bottom.VoiceBottomView;
import com.p046p1.mobile.putong.live.livingroom.voice.bubble.VoiceLiveBubbleView;
import com.p046p1.mobile.putong.live.livingroom.voice.chat.view.VoiceChatBottomView;
import com.p046p1.mobile.putong.live.livingroom.voice.fans.VoiceFansView;
import com.p046p1.mobile.putong.live.livingroom.voice.grabhat.view.VoiceGrabHatFloatViewMode;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.chatgroup.VoiceChatGroupEnterView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.close.VoiceCloseView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.flymic.VoiceFlyMicContainer;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.game.gameRoot.VoiceNewGamePlayRootView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.heartbeat.VoiceTopHeartBeatView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.heatbox.VoiceLiveHeatBoxEntryView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.increment.bullet.VoiceLiveBulletView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.increment.leaderboard.hourleaderboard.widget.VoiceLiveHourBoardEntryView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.newoperation.VoiceNewOperationView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.operations.VoiceOperationsView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.p064pk.VoicePkMvpView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.p064pk.VoicePkTimeView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.preview.VoicePreviewViewModel;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.roombg.common.VoiceBackgroundView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.roominfobar.VoiceRoomInfoView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.root.VoiceLiveView;
import p147v.VFrame;

/* JADX INFO: loaded from: classes4.dex */
public class iwn0 {
    /* JADX INFO: renamed from: a */
    public static void m138757a(VoiceLiveView voiceLiveView, View view) {
        ViewGroup viewGroup = (ViewGroup) view;
        voiceLiveView.f53427d = (VoiceBackgroundView) viewGroup.getChildAt(0);
        voiceLiveView.f53428e = (TouchSwallowView) viewGroup.getChildAt(1);
        voiceLiveView.f53429f = (VoiceFansView) ((ViewGroup) viewGroup.getChildAt(1)).getChildAt(0);
        voiceLiveView.f53430g = (VoiceCloseView) viewGroup.getChildAt(2);
        voiceLiveView.f53431h = (VoicePkMvpView) viewGroup.getChildAt(3);
        voiceLiveView.f53432i = (VoiceRoomInfoView) viewGroup.getChildAt(4);
        voiceLiveView.f53433j = (LiveCampaignView) viewGroup.getChildAt(5);
        voiceLiveView.f53434k = (VoiceNewOperationView) viewGroup.getChildAt(6);
        voiceLiveView.f53435l = (VoiceLiveApplyManagerEnterViewModel) viewGroup.getChildAt(7);
        voiceLiveView.f53436m = (VoiceNewGamePlayRootView) viewGroup.getChildAt(8);
        voiceLiveView.f53437n = (VoiceOperationsView) viewGroup.getChildAt(9);
        voiceLiveView.f53438o = (RecyclerView) ((ViewGroup) viewGroup.getChildAt(9)).getChildAt(0);
        voiceLiveView.f53439p = (FrameLayout) viewGroup.getChildAt(10);
        voiceLiveView.f53440q = (ConstraintLayout) viewGroup.getChildAt(11);
        voiceLiveView.f53441r = (VoiceTopHeartBeatView) ((ViewGroup) viewGroup.getChildAt(11)).getChildAt(0);
        voiceLiveView.f53442s = (IntlLiveStarBoardEntryView) ((ViewGroup) viewGroup.getChildAt(11)).getChildAt(1);
        voiceLiveView.f53443t = (VoiceLiveHourBoardEntryView) ((ViewGroup) viewGroup.getChildAt(11)).getChildAt(2);
        voiceLiveView.f53444u = (VoiceLiveHeatBoxEntryView) ((ViewGroup) viewGroup.getChildAt(11)).getChildAt(3);
        voiceLiveView.f53445v = (VoiceTopNoticeView) ((ViewGroup) viewGroup.getChildAt(11)).getChildAt(4);
        voiceLiveView.f53446w = (VoiceChatGroupEnterView) ((ViewGroup) viewGroup.getChildAt(11)).getChildAt(5);
        voiceLiveView.f53447x = viewGroup.getChildAt(12);
        voiceLiveView.f53448y = (ChatListView) viewGroup.getChildAt(13);
        voiceLiveView.f53449z = (FrameLayout) viewGroup.getChildAt(14);
        voiceLiveView.f53404A = viewGroup.getChildAt(15);
        voiceLiveView.f53405B = (VoicePkTimeView) viewGroup.getChildAt(16);
        voiceLiveView.f53406C = (VoiceGrabHatFloatViewMode) viewGroup.getChildAt(17);
        voiceLiveView.f53407D = (VoiceBottomView) viewGroup.getChildAt(18);
        voiceLiveView.f53408E = (VoiceChatBottomView) ((ViewGroup) viewGroup.getChildAt(18)).getChildAt(0);
        voiceLiveView.f53409F = (BottomMenuView) ((ViewGroup) viewGroup.getChildAt(18)).getChildAt(1);
        voiceLiveView.f53410G = (LiveGiftTrays) viewGroup.getChildAt(19);
        voiceLiveView.f53411H = (DanmakuViewPort) viewGroup.getChildAt(20);
        voiceLiveView.f53412I = (FrameLayout) ((ViewGroup) viewGroup.getChildAt(21)).getChildAt(0);
        voiceLiveView.f53413J = (IntlGiftComboView) ((ViewGroup) viewGroup.getChildAt(22)).getChildAt(0);
        voiceLiveView.f53414K = (VoiceLiveBulletView) viewGroup.getChildAt(23);
        voiceLiveView.f53415L = (VFrame) viewGroup.getChildAt(24);
        voiceLiveView.f53416M = (VoiceFlyMicContainer) ((ViewGroup) viewGroup.getChildAt(24)).getChildAt(0);
        voiceLiveView.f53417N = (LiveGiftLayer) ((ViewGroup) viewGroup.getChildAt(24)).getChildAt(1);
        voiceLiveView.f53418O = (TopEffectLayer) ((ViewGroup) viewGroup.getChildAt(24)).getChildAt(2);
        voiceLiveView.f53419P = (LiveEnterRoomView) viewGroup.getChildAt(25);
        voiceLiveView.f53420Q = (LiveEnterRoomView) viewGroup.getChildAt(25);
        voiceLiveView.f53421R = (VFrame) viewGroup.getChildAt(26);
        voiceLiveView.f53422S = (VoiceLiveBubbleView) ((ViewGroup) viewGroup.getChildAt(26)).getChildAt(0);
        voiceLiveView.f53423T = viewGroup.getChildAt(27);
        voiceLiveView.f53424U = (VoicePreviewViewModel) viewGroup.getChildAt(28);
        voiceLiveView.f53425V = (FrameLayout) viewGroup.getChildAt(29);
    }
}
