package p149l;

import android.view.View;
import android.view.ViewGroup;
import android.view.ViewStub;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.Space;
import android.widget.TextView;
import com.p046p1.mobile.putong.core.newui.home.NewNewProfileCard;
import com.p046p1.mobile.putong.core.newui.home.NewPictureContainerIndicator;
import com.p046p1.mobile.putong.core.newui.home.views.CardBottomDefaultLayout;
import com.p046p1.mobile.putong.core.newui.home.views.CardBottomIntlLiveLayout;
import com.p046p1.mobile.putong.core.newui.home.views.CardBottomIntlVoiceLayout;
import com.p046p1.mobile.putong.core.newui.home.views.CardBottomLiveView;
import com.p046p1.mobile.putong.core.newui.home.views.CardBottomMomentCardTwoView;
import com.p046p1.mobile.putong.core.newui.home.views.CardBottomMomentGreetView;
import com.p046p1.mobile.putong.core.newui.home.views.CardBottomMomentLayout;
import com.p046p1.mobile.putong.core.newui.home.views.CardBottomTagLayout;
import com.p046p1.mobile.putong.core.newui.home.views.SuperLikeBanner;
import com.p046p1.mobile.putong.core.newui.home.views.SwipeLikeButton;
import com.p046p1.mobile.putong.core.newui.view.LinearMeasureOrderLayout;
import com.p046p1.mobile.putong.core.p053ui.PictureView;
import com.p046p1.mobile.putong.core.p053ui.likeminded.LikeMindedCardTabView;
import com.tantan.library.svga.SVGAnimationView;
import p147v.VDraweeView;
import p147v.VFrame;
import p147v.VIcon;
import p147v.VImage;
import p147v.VLinear;
import p147v.VText;

/* JADX INFO: loaded from: classes10.dex */
public class iz30 {
    /* JADX INFO: renamed from: a */
    public static void m139025a(NewNewProfileCard newNewProfileCard, View view) {
        newNewProfileCard.f21715M = (NewNewProfileCard) view;
        ViewGroup viewGroup = (ViewGroup) view;
        newNewProfileCard.f21719N = (LinearLayout) viewGroup.getChildAt(0);
        newNewProfileCard.f21722O = ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(0);
        newNewProfileCard.f21725P = (VLinear) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(1);
        newNewProfileCard.f21728Q = ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(1)).getChildAt(0);
        newNewProfileCard.f21731R = (CardBottomMomentCardTwoView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(1)).getChildAt(1);
        newNewProfileCard.f21734S = ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(1)).getChildAt(2);
        newNewProfileCard.f21737T = (PictureView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(2);
        newNewProfileCard.f21740U = (Space) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(3);
        newNewProfileCard.f21743V = ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(4);
        newNewProfileCard.f21746W = ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(5);
        newNewProfileCard.f21775k0 = ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(6);
        newNewProfileCard.f21786p0 = ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(7);
        newNewProfileCard.f21691E0 = (LinearMeasureOrderLayout) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8);
        newNewProfileCard.f21694F0 = (VFrame) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(0);
        newNewProfileCard.f21697G0 = (SVGAnimationView) ((ViewGroup) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(0)).getChildAt(0);
        newNewProfileCard.f21700H0 = (VText) ((ViewGroup) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(0)).getChildAt(1);
        newNewProfileCard.f21703I0 = (TextView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(1);
        newNewProfileCard.f21706J0 = (VText) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(2);
        newNewProfileCard.f21709K0 = (VText) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(3);
        newNewProfileCard.f21712L0 = (VLinear) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(4);
        newNewProfileCard.f21716M0 = (ImageView) ((ViewGroup) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(4)).getChildAt(0);
        newNewProfileCard.f21720N0 = (TextView) ((ViewGroup) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(4)).getChildAt(1);
        newNewProfileCard.f21723O0 = (VText) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(5);
        newNewProfileCard.f21726P0 = (VText) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(6);
        newNewProfileCard.f21729Q0 = (VLinear) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(7);
        newNewProfileCard.f21732R0 = (VDraweeView) ((ViewGroup) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(7)).getChildAt(0);
        newNewProfileCard.f21735S0 = (VText) ((ViewGroup) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(7)).getChildAt(1);
        newNewProfileCard.f21738T0 = (VText) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(8);
        newNewProfileCard.f21741U0 = (VImage) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(8)).getChildAt(9);
        newNewProfileCard.f21744V0 = (FrameLayout) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(9);
        newNewProfileCard.f21747W0 = (CardBottomLiveView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(9)).getChildAt(0);
        newNewProfileCard.f21749X0 = (CardBottomMomentGreetView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(9)).getChildAt(1);
        newNewProfileCard.f21751Y0 = (CardBottomDefaultLayout) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(9)).getChildAt(2);
        newNewProfileCard.f21753Z0 = (CardBottomIntlLiveLayout) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(9)).getChildAt(3);
        newNewProfileCard.f21755a1 = (CardBottomIntlVoiceLayout) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(9)).getChildAt(4);
        newNewProfileCard.f21757b1 = (CardBottomTagLayout) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(9)).getChildAt(5);
        newNewProfileCard.f21759c1 = (CardBottomMomentLayout) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(9)).getChildAt(6);
        newNewProfileCard.f21761d1 = (VLinear) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(10);
        newNewProfileCard.f21763e1 = (VIcon) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(11);
        newNewProfileCard.f21765f1 = (VImage) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(12);
        newNewProfileCard.f21767g1 = (VImage) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(13);
        newNewProfileCard.f21769h1 = (ViewStub) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(14);
        newNewProfileCard.f21771i1 = (ViewStub) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(15);
        newNewProfileCard.f21773j1 = (LikeMindedCardTabView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(16);
        newNewProfileCard.f21776k1 = (VLinear) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(17);
        newNewProfileCard.f21778l1 = (VText) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(17)).getChildAt(1);
        newNewProfileCard.f21780m1 = (ViewStub) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(18);
        newNewProfileCard.f21782n1 = (ViewStub) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(19);
        newNewProfileCard.f21784o1 = (ViewStub) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(20);
        newNewProfileCard.f21787p1 = (SuperLikeBanner) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(21);
        newNewProfileCard.f21789q1 = (SwipeLikeButton) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(22);
        newNewProfileCard.f21791r1 = (SwipeLikeButton) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(23);
        newNewProfileCard.f21793s1 = (NewPictureContainerIndicator) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(24);
        newNewProfileCard.f21795t1 = (ViewStub) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(25);
        newNewProfileCard.f21797u1 = (ViewStub) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(26);
        newNewProfileCard.f21799v1 = (ViewStub) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(27);
        newNewProfileCard.f21801w1 = (ViewStub) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(28);
        newNewProfileCard.f21803x1 = (ViewStub) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(29);
        newNewProfileCard.f21805y1 = (LinearLayout) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(30);
        newNewProfileCard.f21807z1 = (VText) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(30)).getChildAt(1);
        newNewProfileCard.f21683A1 = (LinearLayout) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(31);
        newNewProfileCard.f21685B1 = (VText) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(0)).getChildAt(0)).getChildAt(31)).getChildAt(1);
        newNewProfileCard.f21687C1 = (VFrame) viewGroup.getChildAt(1);
        newNewProfileCard.f21689D1 = (ViewStub) ((ViewGroup) viewGroup.getChildAt(1)).getChildAt(0);
    }
}
