package p149l;

import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import com.p046p1.mobile.putong.live.livingroom.base.live.LiveView;
import com.p046p1.mobile.putong.live.livingroom.base.preview.PreviewView;
import com.p046p1.mobile.putong.live.livingroom.base.pusher.LivePusherView;
import com.p046p1.mobile.putong.live.livingroom.base.room.LiveBgView;
import com.p046p1.mobile.putong.live.livingroom.common.avatar.AvatarView;
import com.p046p1.mobile.putong.live.livingroom.common.bottom.sticker.LiveStickerContainer;
import com.p046p1.mobile.putong.live.livingroom.common.bottom.sticker.LiveStickerDragMask;
import com.p046p1.mobile.putong.live.livingroom.common.bottom.view.BottomView;
import com.p046p1.mobile.putong.live.livingroom.common.bubble.LiveBubbleView;
import com.p046p1.mobile.putong.live.livingroom.common.chat.ChatView;
import com.p046p1.mobile.putong.live.livingroom.common.chat.danmaku.show.DanmakuViewPort;
import com.p046p1.mobile.putong.live.livingroom.common.chat.inputEntry.ChatInputEntryView;
import com.p046p1.mobile.putong.live.livingroom.common.fans.FansView;
import com.p046p1.mobile.putong.live.livingroom.increment.bullet.BulletView;
import com.p046p1.mobile.putong.live.livingroom.increment.campaign.LiveCampaignView;
import com.p046p1.mobile.putong.live.livingroom.increment.gift.game.GameEffectView;
import com.p046p1.mobile.putong.live.livingroom.increment.gift.giftlayer.LiveGiftLayer;
import com.p046p1.mobile.putong.live.livingroom.increment.gift.topeffect.view.TopEffectLayer;
import com.p046p1.mobile.putong.live.livingroom.increment.gift.tray.LiveEnterRoomView;
import com.p046p1.mobile.putong.live.livingroom.increment.gift.tray.LiveGiftTrays;
import com.p046p1.mobile.putong.live.livingroom.increment.leaderboard.hourleaderboard.entry.HourBoardEntryView;
import com.p046p1.mobile.putong.live.livingroom.increment.leaderboard.hourleaderboard.entry.HourBoardNewEntryView;
import com.p046p1.mobile.putong.live.livingroom.increment.leaderboard.intlstarboard.IntlLiveStarBoardEntryView;
import com.p046p1.mobile.putong.live.livingroom.increment.leaderboard.starboard.StarBoardEntryView;
import com.p046p1.mobile.putong.live.livingroom.increment.operation.OperationEntryView;
import com.p046p1.mobile.putong.live.livingroom.increment.operation.PreOperationAnimView;
import com.p046p1.mobile.putong.live.livingroom.other.obs.ObsPreviewView;
import com.p046p1.mobile.putong.live.livingroom.recreation.multiCall.annoncements.view.LiveAnnouncementEntryView;
import com.p046p1.mobile.putong.live.livingroom.recreation.multiCall.view.MultiCallTopView;
import com.p046p1.mobile.putong.live.livingroom.recreation.multiPk.multiPkPlaying.MultiPkTimerView;
import com.p046p1.mobile.putong.live.livingroom.recreation.multiplayerchat.view.CallWidgetView;
import com.p046p1.mobile.putong.live.livingroom.recreation.multiplayerchat.view.LiveCallView;
import com.p046p1.mobile.putong.live.livingroom.recreation.p062pk.PkView;
import com.p046p1.mobile.putong.live.livingroom.recreation.p062pk.internal.PkViewInternal;
import p147v.VFrame;
import p147v.VImage;
import p147v.VRelative;

/* JADX INFO: loaded from: classes4.dex */
public class jwu {
    /* JADX INFO: renamed from: a */
    public static void m143672a(LiveView liveView, View view) {
        ViewGroup viewGroup = (ViewGroup) view;
        liveView.f47824a = (LiveBgView) viewGroup.getChildAt(0);
        liveView.f47825b = (LivePusherView) viewGroup.getChildAt(1);
        liveView.f47826c = (PreviewView) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(0);
        liveView.f47827d = (PkView) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(1);
        liveView.f47828e = (PkViewInternal) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(2);
        liveView.f47829f = (MultiCallTopView) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(3);
        liveView.f47830g = (MultiPkTimerView) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(4);
        liveView.f47831h = (ObsPreviewView) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(5);
        liveView.f47832i = (LiveCallView) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(6);
        liveView.f47833j = (VFrame) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(7);
        liveView.f47834k = (AvatarView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(7)).getChildAt(0);
        liveView.f47835l = ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(8);
        liveView.f47836m = (VRelative) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(9);
        liveView.f47837n = (LiveAnnouncementEntryView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(9)).getChildAt(0);
        liveView.f47838o = (VFrame) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(9)).getChildAt(1);
        liveView.f47839p = (HourBoardEntryView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(9)).getChildAt(1)).getChildAt(0);
        liveView.f47840q = (HourBoardNewEntryView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(9)).getChildAt(1)).getChildAt(1);
        liveView.f47841r = (FrameLayout) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(9)).getChildAt(2);
        liveView.f47842s = (StarBoardEntryView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(9)).getChildAt(2)).getChildAt(0);
        liveView.f47843t = (IntlLiveStarBoardEntryView) ((ViewGroup) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(9)).getChildAt(2)).getChildAt(1);
        liveView.f47844u = (FansView) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(10);
        liveView.f47845v = (BulletView) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(11);
        liveView.f47846w = (LiveStickerContainer) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(12);
        liveView.f47847x = (OperationEntryView) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(13);
        liveView.f47848y = ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(14);
        liveView.f47849z = (CallWidgetView) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(15);
        liveView.f47801A = (DanmakuViewPort) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(16);
        liveView.f47802B = (ChatView) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(17);
        liveView.f47803C = (LiveCampaignView) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(18);
        liveView.f47804D = (FrameLayout) ((ViewGroup) viewGroup.getChildAt(2)).getChildAt(19);
        liveView.f47805E = (VFrame) viewGroup.getChildAt(3);
        liveView.f47806F = (LiveGiftLayer) ((ViewGroup) viewGroup.getChildAt(3)).getChildAt(0);
        liveView.f47807G = (TopEffectLayer) ((ViewGroup) viewGroup.getChildAt(3)).getChildAt(1);
        liveView.f47808H = (VRelative) viewGroup.getChildAt(4);
        liveView.f47809I = (ChatInputEntryView) ((ViewGroup) viewGroup.getChildAt(4)).getChildAt(0);
        liveView.f47810J = (BottomView) ((ViewGroup) viewGroup.getChildAt(4)).getChildAt(1);
        liveView.f47811K = (LiveBubbleView) ((ViewGroup) viewGroup.getChildAt(4)).getChildAt(2);
        liveView.f47812L = (LiveGiftTrays) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(4)).getChildAt(3)).getChildAt(0);
        liveView.f47813M = (LiveEnterRoomView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(4)).getChildAt(3)).getChildAt(1);
        liveView.f47814N = (LiveEnterRoomView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(4)).getChildAt(3)).getChildAt(1);
        liveView.f47815O = (FrameLayout) ((ViewGroup) viewGroup.getChildAt(4)).getChildAt(4);
        liveView.f47816P = (VRelative) viewGroup.getChildAt(5);
        liveView.f47817Q = (VImage) ((ViewGroup) viewGroup.getChildAt(5)).getChildAt(0);
        liveView.f47818R = (LiveStickerDragMask) viewGroup.getChildAt(6);
        liveView.f47819S = viewGroup.getChildAt(7);
        liveView.f47820T = (PreOperationAnimView) viewGroup.getChildAt(8);
        liveView.f47821U = (GameEffectView) viewGroup.getChildAt(9);
        liveView.f47822V = (VFrame) viewGroup.getChildAt(10);
    }
}
