package p149l;

import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import com.p046p1.mobile.putong.live.livingroom.common.chat.danmaku.show.DanmakuViewPort;
import com.p046p1.mobile.putong.live.livingroom.common.chat.list.ChatListView;
import com.p046p1.mobile.putong.live.livingroom.increment.campaign.LiveCampaignView;
import com.p046p1.mobile.putong.live.livingroom.increment.gift.giftlayer.LiveGiftLayer;
import com.p046p1.mobile.putong.live.livingroom.increment.gift.topeffect.view.TopEffectLayer;
import com.p046p1.mobile.putong.live.livingroom.increment.gift.tray.LiveEnterRoomView;
import com.p046p1.mobile.putong.live.livingroom.increment.gift.tray.LiveGiftTrays;
import com.p046p1.mobile.putong.live.livingroom.increment.leaderboard.intlstarboard.IntlLiveStarBoardEntryView;
import com.p046p1.mobile.putong.live.livingroom.intl.gift.IntlGiftComboView;
import com.p046p1.mobile.putong.live.livingroom.view.TouchSwallowView;
import com.p046p1.mobile.putong.live.livingroom.voice.applymanager.VoiceLiveApplyManagerEnterViewModel;
import com.p046p1.mobile.putong.live.livingroom.voice.basebuild.notice.VoiceTopNoticeView;
import com.p046p1.mobile.putong.live.livingroom.voice.bottom.BottomMenuView;
import com.p046p1.mobile.putong.live.livingroom.voice.bottom.VoiceBottomView;
import com.p046p1.mobile.putong.live.livingroom.voice.bubble.VoiceLiveBubbleView;
import com.p046p1.mobile.putong.live.livingroom.voice.chat.view.VoiceChatBottomView;
import com.p046p1.mobile.putong.live.livingroom.voice.fans.VoiceFansView;
import com.p046p1.mobile.putong.live.livingroom.voice.grabhat.view.VoiceGrabHatFloatViewMode;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.chatgroup.VoiceChatGroupEnterView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.close.VoiceCloseView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.flymic.VoiceFlyMicContainer;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.game.gameRoot.VoiceNewGamePlayRootView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.heartbeat.VoiceTopHeartBeatView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.heatbox.VoiceLiveHeatBoxEntryView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.increment.bullet.VoiceLiveBulletView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.increment.leaderboard.hourleaderboard.widget.VoiceLiveHourBoardEntryView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.newoperation.VoiceNewOperationView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.operations.VoiceOperationsView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.p064pk.VoicePkMvpView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.p064pk.VoicePkTimeView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.player.VoiceIncomeAreaStateView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.player.VoiceOrignalStateView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.player.VoiceRoomLoadingView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.roombg.common.VoiceBackgroundView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.roominfobar.VoiceRoomInfoView;
import com.p046p1.mobile.putong.live.livingroom.voice.intl.root.VoiceRoomView;
import p147v.VFrame;

/* JADX INFO: loaded from: classes4.dex */
public class oio0 {
    /* JADX INFO: renamed from: a */
    public static void m164542a(VoiceRoomView voiceRoomView, View view) {
        voiceRoomView.f53481d = (VoiceRoomView) view;
        ViewGroup viewGroup = (ViewGroup) view;
        voiceRoomView.f53482e = (VoiceBackgroundView) viewGroup.getChildAt(0);
        voiceRoomView.f53483f = (TouchSwallowView) viewGroup.getChildAt(1);
        voiceRoomView.f53484g = (VoiceFansView) ((ViewGroup) viewGroup.getChildAt(1)).getChildAt(0);
        voiceRoomView.f53485h = (VoiceCloseView) viewGroup.getChildAt(2);
        voiceRoomView.f53486i = (VoicePkMvpView) viewGroup.getChildAt(3);
        voiceRoomView.f53487j = (VoiceRoomInfoView) viewGroup.getChildAt(4);
        voiceRoomView.f53488k = (LiveCampaignView) viewGroup.getChildAt(5);
        voiceRoomView.f53490l = (VoiceNewOperationView) viewGroup.getChildAt(6);
        voiceRoomView.f53491m = (FrameLayout) viewGroup.getChildAt(7);
        voiceRoomView.f53492n = (TouchSwallowView) viewGroup.getChildAt(8);
        voiceRoomView.f53493o = (VoiceOperationsView) ((ViewGroup) viewGroup.getChildAt(8)).getChildAt(0);
        voiceRoomView.f53494p = (RecyclerView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(8)).getChildAt(0)).getChildAt(0);
        voiceRoomView.f53496q = (ConstraintLayout) viewGroup.getChildAt(9);
        voiceRoomView.f53497r = (VoiceTopHeartBeatView) ((ViewGroup) viewGroup.getChildAt(9)).getChildAt(0);
        voiceRoomView.f53498s = (IntlLiveStarBoardEntryView) ((ViewGroup) viewGroup.getChildAt(9)).getChildAt(1);
        voiceRoomView.f53499t = (VoiceLiveHourBoardEntryView) ((ViewGroup) viewGroup.getChildAt(9)).getChildAt(2);
        voiceRoomView.f53500u = (VoiceLiveHeatBoxEntryView) ((ViewGroup) viewGroup.getChildAt(9)).getChildAt(3);
        voiceRoomView.f53501v = (VoiceTopNoticeView) ((ViewGroup) viewGroup.getChildAt(9)).getChildAt(4);
        voiceRoomView.f53502w = (VoiceChatGroupEnterView) ((ViewGroup) viewGroup.getChildAt(9)).getChildAt(5);
        voiceRoomView.f53503x = (VoiceLiveApplyManagerEnterViewModel) viewGroup.getChildAt(10);
        voiceRoomView.f53504y = (VoiceIncomeAreaStateView) viewGroup.getChildAt(11);
        voiceRoomView.f53505z = (VFrame) viewGroup.getChildAt(12);
        voiceRoomView.f53450A = (VoiceOrignalStateView) ((ViewGroup) viewGroup.getChildAt(12)).getChildAt(0);
        voiceRoomView.f53451B = (VoiceNewGamePlayRootView) viewGroup.getChildAt(13);
        voiceRoomView.f53452C = viewGroup.getChildAt(14);
        voiceRoomView.f53453D = (TouchSwallowView) viewGroup.getChildAt(15);
        voiceRoomView.f53454E = (ChatListView) ((ViewGroup) viewGroup.getChildAt(15)).getChildAt(0);
        voiceRoomView.f53456F = (VoicePkTimeView) viewGroup.getChildAt(16);
        voiceRoomView.f53458G = (VoiceGrabHatFloatViewMode) viewGroup.getChildAt(17);
        voiceRoomView.f53460H = (FrameLayout) viewGroup.getChildAt(18);
        voiceRoomView.f53462I = viewGroup.getChildAt(19);
        voiceRoomView.f53464J = (TouchSwallowView) viewGroup.getChildAt(20);
        voiceRoomView.f53466K = (VoiceBottomView) ((ViewGroup) viewGroup.getChildAt(20)).getChildAt(0);
        voiceRoomView.f53468L = (VoiceChatBottomView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(20)).getChildAt(0)).getChildAt(0);
        voiceRoomView.f53470M = (BottomMenuView) ((ViewGroup) ((ViewGroup) viewGroup.getChildAt(20)).getChildAt(0)).getChildAt(1);
        voiceRoomView.f53471N = (VoiceRoomLoadingView) viewGroup.getChildAt(21);
        voiceRoomView.f53472O = (TouchSwallowView) viewGroup.getChildAt(22);
        voiceRoomView.f53473P = (LiveGiftTrays) ((ViewGroup) viewGroup.getChildAt(22)).getChildAt(0);
        voiceRoomView.f53474Q = (DanmakuViewPort) viewGroup.getChildAt(23);
        voiceRoomView.f53475R = (TouchSwallowView) viewGroup.getChildAt(24);
        voiceRoomView.f53476S = (FrameLayout) ((ViewGroup) viewGroup.getChildAt(24)).getChildAt(0);
        voiceRoomView.f53477T = (IntlGiftComboView) ((ViewGroup) viewGroup.getChildAt(25)).getChildAt(0);
        voiceRoomView.f53478U = (VoiceLiveBulletView) viewGroup.getChildAt(26);
        voiceRoomView.f53479V = (VFrame) viewGroup.getChildAt(27);
        voiceRoomView.f53480W = (VoiceFlyMicContainer) ((ViewGroup) viewGroup.getChildAt(27)).getChildAt(0);
        voiceRoomView.f53489k0 = (LiveGiftLayer) ((ViewGroup) viewGroup.getChildAt(27)).getChildAt(1);
        voiceRoomView.f53495p0 = (TopEffectLayer) ((ViewGroup) viewGroup.getChildAt(27)).getChildAt(2);
        voiceRoomView.f53455E0 = (LiveEnterRoomView) viewGroup.getChildAt(28);
        voiceRoomView.f53457F0 = (LiveEnterRoomView) viewGroup.getChildAt(28);
        voiceRoomView.f53459G0 = (VFrame) viewGroup.getChildAt(29);
        voiceRoomView.f53461H0 = (VoiceLiveBubbleView) ((ViewGroup) viewGroup.getChildAt(29)).getChildAt(0);
        voiceRoomView.f53463I0 = ((ViewGroup) viewGroup.getChildAt(29)).getChildAt(1);
        voiceRoomView.f53465J0 = (FrameLayout) viewGroup.getChildAt(30);
    }
}
